module.exports = {
    NO_SUCCESS_CALLBACK: "No success callback was found. You have to specify it.",
    NO_ERROR_CALLBACK: "No error callback was found. You have to specify it.",
    NO_EMAIL: "Email was not specified.",
    NO_OLD_PASSWORD: "Old password was not specified.",
    NO_PASSWORD: "Password was not specified.",
    NO_ROLES: "Roles were not specified.",
    NO_ID: "ID was not specified.",
    NO_USER_ID: "User ID was not specified.",
    NO_USER_IDS: "No user ids were specified.",
    NO_PLATFORM_ID: "No id was specified.",
    NO_PLATFORM_USER_ID: "No user id was specified.",
    NO_PLATFORM_NAME: "Platform name was not specified.",
    NO_PLATFORM_REGISTRATION_ID: "Registration id was not specified.",
    NO_PATH: "Path of the file was not specified.",
    NO_FILE: "File was not specified.",
    NO_URL: "Url was not specified.",
    NO_SUBJECT: "Subject was not specified.",
    NO_SYNERGYKIT_OBJECT: "Synergykit object was not specified.",
    NO_AUTH_DATA: "No authData was specified.",
    NO_FACEBOOK_DATA: "No facebook data was specified.",
    NO_FACEBOOK_ID: "No facebook id was specified.",
    NO_FACEBOOK_ACCESS_TOKEN: "No facebook access token was specified.",
    NO_TWITTER_DATA: "No twitter data was speicfied.",
    NO_TWITTER_ID: "No twitter id was specified.",
    NO_TWITTER_SCREEN_NAME: "No twitter screen name was specified.",
    NO_TWITTER_CONSUMER_KEY: "No twitter consumer key was specified.",
    NO_TWITTER_CONSUMER_SECRET: "No twitter consumer secret was specified.",
    NO_TWITTER_AUTH_TOKEN: "No twitter auth token was specified.",
    NO_TWITTER_AUTH_TOKEN_SECRET: "No twitter auth token secret was specified.",
    NO_GOOGLE_DATA: "No google data was specified.",
    NO_GOOGLE_ID: "No google id was specified.",
    NO_ANONYMOUS_DATA: "No anonymous data was specified."
}