module.exports = {
    NO_SUCCESS_CALLBACK: "No success callback was found. You have to specify it.",
    NO_ERROR_CALLBACK: "No error callback was found. You have to specify it.",
    NO_EMAIL: "Email was not specified.",
    NO_PASSWORD: "Password was not specified.",
    NO_ROLES: "Roles were not specified.",
    NO_ID: "ID was not specified.",
    NO_USER_ID: "User ID was not specified.",
    NO_USER_IDS: "No user ids were specified.",
    NO_PLATFORM_ID: "No id was specified.",
    NO_PLATFORM_USER_ID: "No user id was specified.",
    NO_PLATFORM_NAME: "Platform name was not specified.",
    NO_PLATFORM_REGISTRATION_ID: "Registration id was not specified.",
    NO_PATH: "Path of the file was not specified.",
    NO_FILE: "File was not specified.",
    NO_URL: "Url was not specified.",
    NO_SUBJECT: "Subject was not specified.",
    NO_SYNERGYKIT_OBJECT: "Synergykit object was not specified.",
}